version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: data from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after:
            count: 90
            period: day
        columns:
          - name: date_date
            description: purchase date
          - name: orders_id
            description: orders unique identifiant 
          - name: pdt_id
            description: product unique identifiant
          - name: revenue
            description: purchase amount
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id )"
          - not_null:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: product of Greenweez / we have on row per product_id found with purchase price
        tests:
          - unique:
              column_name: "products_id"
          - not_null:
              column_name: "products_id"
        columns:
          - name: products_id
            description: product unique identifiant
          - name: purchSE_PRICE
            description: purchase price
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez / we have on row per order_id found with shipping fee, log cost, ship cost
        tests:
          - unique:
              column_name: "orders_id"
          - not_null:
              column_name: "orders_id"
        columns:
          - name: orders_id
            description: orders unique identifiant 
          - name: shipping_fee
            description: shipping fee
          - name: logCost
            description: logistic cost
          - name: ship_Cost
            description: ship cost

